name: Render Quarto
on:
  push:
    paths:
      - 'README.qmd'
      - '.github/workflows/quarto-render.yml'

jobs:
  quarto-render:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        
      - name: Render README
        run: |
          quarto render README.qmd --profile default
        
      - name: Commit README.md
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add README.md smoother_example.png
          git commit -m "Re-render README.md" || echo "No changes to commit"
          git push origin || echo "No changes to push"