coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch: off

ignore:
  - "src/extensions/**/*"  # Ignore everything in the extensions directory

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false