name: Documentation

on:
  push:
    branches:
      - main
    tags: '*'
    paths:
      - 'docs/**'
      - 'src/**'
      - '.github/workflows/documentation.yml'
  pull_request:
    paths:
      - 'docs/**'
      - 'src/**'
      - '.github/workflows/documentation.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: '1.11.3'

      - name: Install dependencies
        run: |
          julia --project=docs -e '
            using Pkg
            Pkg.instantiate()
            Pkg.develop(PackageSpec(path=pwd()))
          '

      - name: Cache Julia packages
        uses: actions/cache@v3
        with:
          path: ~/.julia
          key: ${{ runner.os }}-${{ matrix.julia-version }}-${{ hashFiles('**/Project.toml') }}

      - name: Build Documenter.jl docs
        run: |
          julia --project=docs docs/make.jl

      - name: Install Netlify CLI
        run: npm install -g netlify-cli

      - name: Deploy to Netlify
        if: github.event_name == 'push' && (startsWith(github.ref, 'refs/tags/') || github.ref == 'refs/heads/main')
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        run: |
          netlify deploy --dir=docs/build --prod --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN
