name: Documentation

on:
  push:
    branches:
      - main
    tags: '*'
    paths:
      - 'docs/**'
      - 'src/**'
      - '.github/workflows/documentation.yml'
  pull_request:
    paths:
      - 'docs/**'
      - 'src/**'
      - '.github/workflows/documentation.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: '1.9'

      - name: Install Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: '1.3.450'

      - name: Install dependencies
        run: |
          julia --project=docs -e '
            using Pkg
            Pkg.develop(PackageSpec(path=pwd()))
            Pkg.instantiate()'

      - name: Build Documenter.jl docs
        run: |
          julia --project=docs docs/make.jl

      - name: Build Quarto docs
        run: |
          cd docs/quarto
          quarto render

      - name: Deploy
        if: github.event_name == 'push' && (startsWith(github.ref, 'refs/tags/') || github.ref == 'refs/heads/main')
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs/_site  # Combined output directory
          branch: gh-pages