name: Documentation

on:
  push:
    branches:
      - main
    tags: '*'
    paths:
      - 'docs/**'
      - 'src/**'
      - '.github/workflows/documentation.yml'
  pull_request:
    paths:
      - 'docs/**'
      - 'src/**'
      - '.github/workflows/documentation.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: '1.11.3'

      - name: Install dependencies
        run: |
          julia --project=docs -e '
            using Pkg
            Pkg.instantiate()  # First install docs deps
            Pkg.develop(PackageSpec(path=pwd()))  # Then add main package
          '

      - name: Cache Julia packages
        uses: actions/cache@v3
        with:
          path: ~/.julia
          key: ${{ runner.os }}-${{ matrix.julia-version }}-${{ hashFiles('**/Project.toml') }}

      - name: Build Documenter.jl docs
        run: |
          julia --project=docs docs/make.jl

      - name: Deploy
        if: github.event_name == 'push' && (startsWith(github.ref, 'refs/tags/') || github.ref == 'refs/heads/main')
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs/build
          branch: gh-pages